cp lib/generateHtml.py exec/generateHtml.py
cp lib/oracleconnect.py exec/oracleconnect.py
cp webpage/webpageCreater.py exec/webpageCreater.py
cp webpage/HP_New_Logo_2D.png exec/HP_New_Logo_2D.png
cp webpage/InservImage.jpg exec/InservImage.jpg
cp webpage/inservPage.py exec/inservPage.py
cp webpage/NewDemo.py exec/NewDemo.py
cp webpage/report_data.py exec/report_data.py
cp webpage/3par_arrays.jpg exec/3par_arrays.jpg
cp webpage/ExecutiveRpt.py exec/ExecutiveRpt.py
cp webpage/SalesReporting.py exec/SalesReporting.py
cp parser/filenameloader.py exec/filenameloader.py
cp parser/filenameloadert2below.py exec/filenameloadert2below.py
cp parser/filenameloadertiertwo.py exec/filenameloadertiertwo.py
cp parser/loaderlib.py exec/loaderlib.py
cp parser/hostlib.py exec/hostlib.py
cp parser/MachineAdd.py exec/MachineAdd.py
cp parser/machinestatus.py exec/machinestatus.py
cp parser/machinestatus.sh exec/machinestatus.sh
cp parser/parser.py exec/parser.py
cp parser/statsfilelib.py exec/statsfilelib.py
cp parser/statslog.py exec/statslog.py
cp parser/initialbuild_vm.py exec/initialbuild_vm.py
cp parser/mysqlconnect.py exec/mysqlconnect.py
cp install.sh exec/install.sh
cp parser/CopyConfigLib.py exec/CopyConfigLib.py
cp parser/dataCopy.py exec/dataCopy.py
cp parser/statsprocessor.py exec/statsprocessor.py
cp parser/processinglib.py exec/processinglib.py
cp parser/parsetabber.py exec/parsetabber.py
cp parser/copymeta.py exec/copymeta.py
cp parser/copydatatoods.py exec/copydatatoods.py
cd exec
rm -rf web.zip
zip web generateHtml.py oracleconnect.py webpageCreater.py HP_New_Logo_2D.png InservImage.jpg inservPage.py NewDemo.py report_data.py 3par_arrays.jpg ExecutiveRpt.py SalesReporting.py hostlib.py 
rm -rf parser.zip
zip parser filenameloader.py oracleconnect.py loaderlib.py hostlib.py MachineAdd.py install.sh machinestatus.py machinestatus.sh parser.py statsfilelib.py statslog.py filenameloadert2below.py filenameloadertiertwo.py initialbuild_vm.py mysqlconnect.py CopyConfigLib.py dataCopy.py statsprocessor.py processinglib.py parsetabber.py copymeta.py copydatatoods.py
rm -rf generateHtml.py
rm -rf oracleconnect.py
rm -rf webpageCreater.py
rm -rf HP_New_Logo_2D.png
rm -rf InservImage.jpg
rm -rf NewDemo.py
rm -rf report_data.py
rm -rf 3par_arrays.jpg
rm -rf ExecutiveRpt.py
rm -rf inservPage.py
rm -rf SalesReporting.py
rm -rf filenameloader.py
rm -rf loaderlib.py
rm -rf hostlib.py
rm -rf MachineAdd.py
rm -rf install.sh
rm -rf machinestatus.*
rm -rf parser.py
rm -rf statsfilelib.py
rm -rf statslog.py
rm -rf filenameloadert2below.py
rm -rf filenameloadertiertwo.py
rm -rf initialbuild_vm.py
rm -rf mysqlconnect.py
rm -rf CopyConfigLib.py
rm -rf dataCopy.py
rm -rf statsprocessor.py
rm -rf parsetabber.py
rm -rf copymeta.py
rm -rf copydatatoods.py
